name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Docker username env
        run: echo "DOCKER_USER=${{ secrets.DOCKER_USER }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # ============================
      # BUILD SERVICES
      # ============================

      - name: Build Gateway
        run: docker build -t "$DOCKER_USER/market-gateway:latest" Getway_market/

      - name: Build User Service
        run: docker build -t "$DOCKER_USER/market-user_service:latest" marketplaceUserService/

      - name: Build Product Service
        run: docker build -t "$DOCKER_USER/market-product_service:latest" Product_Service/

      # ============================
      # PUSH IMAGES
      # ============================

      - name: Push Images
        run: |
          docker push "$DOCKER_USER/market-gateway:latest"
          docker push "$DOCKER_USER/market-user_service:latest"
          docker push "$DOCKER_USER/market-product_service:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set Docker username env
        run: echo "DOCKER_USER=${{ secrets.DOCKER_USER }}" >> $GITHUB_ENV

      - name: Deploy to Swarm
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            docker pull "$DOCKER_USER/market-gateway:latest"
            docker pull "$DOCKER_USER/market-user_service:latest"
            docker pull "$DOCKER_USER/market-product_service:latest"

            cd /home/project/market
            docker stack deploy -c stack.yml market
